#!/usr/bin/env python3
"""
TFNK™ Setup Script
Prepares the environment for running the TFNK™ Neural Agent Desktop.
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path

# ─── ANSI colour helpers ──────────────────────────────────────────────────────

RESET  = "\033[0m"
BOLD   = "\033[1m"
RED    = "\033[91m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
CYAN   = "\033[96m"
WHITE  = "\033[97m"

def ok(msg: str)   -> None: print(f"  {GREEN}[OK]{RESET}  {msg}")
def warn(msg: str) -> None: print(f"  {YELLOW}[WARN]{RESET} {msg}")
def err(msg: str)  -> None: print(f"  {RED}[ERR]{RESET} {msg}")
def info(msg: str) -> None: print(f"  {CYAN}[--]{RESET}  {msg}")
def hdr(msg: str)  -> None: print(f"\n{BOLD}{WHITE}{msg}{RESET}")

# ─── Root of the project ──────────────────────────────────────────────────────

ROOT = Path(__file__).resolve().parent.parent

# ─── Checks ───────────────────────────────────────────────────────────────────

def check_python() -> bool:
    hdr("Python version")
    major, minor = sys.version_info[:2]
    version_str = f"{major}.{minor}.{sys.version_info[2]}"
    if major < 3 or (major == 3 and minor < 11):
        err(f"Python {version_str} detected — Python 3.11+ is required.")
        err("  Download: https://www.python.org/downloads/")
        return False
    ok(f"Python {version_str}")
    return True


def check_pip() -> bool:
    hdr("pip availability")
    if shutil.which("pip") or shutil.which("pip3"):
        ok("pip found")
        return True
    err("pip not found — install pip: https://pip.pypa.io/en/stable/installation/")
    return False


def install_requirements() -> bool:
    hdr("Installing Python dependencies")
    req_file = ROOT / "requirements.txt"
    if not req_file.exists():
        warn("requirements.txt not found — skipping dependency installation.")
        return True
    try:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-r", str(req_file)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
        )
        ok(f"Installed packages from {req_file.name}")
        return True
    except subprocess.CalledProcessError as exc:
        err(f"pip install failed: {exc}")
        return False


def create_env() -> bool:
    hdr(".env configuration")
    env_file     = ROOT / ".env"
    env_example  = ROOT / ".env.example"
    if env_file.exists():
        ok(".env already exists — skipping.")
        return True
    if env_example.exists():
        shutil.copy(env_example, env_file)
        ok(".env created from .env.example")
        warn("Review .env and fill in any required secrets before running.")
        return True
    warn(".env.example not found — creating minimal .env placeholder.")
    env_file.write_text(
        "# TFNK™ environment configuration\n"
        "# Generated by scripts/setup.py\n\n"
        "TFNK_HOST=0.0.0.0\n"
        "TFNK_PORT=8000\n"
        "TFNK_LOG_LEVEL=info\n"
        "OLLAMA_BASE_URL=http://localhost:11434\n"
        "WHISPER_MODEL=base\n",
        encoding="utf-8",
    )
    ok(".env placeholder written.")
    return True


def create_directories() -> bool:
    hdr("Directory structure")
    dirs = [
        ROOT / "logs",
        ROOT / "memory",
        ROOT / "skills",
        ROOT / "backups",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        # Place a .gitkeep so the directory is tracked by git
        gitkeep = d / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.touch()
        ok(f"{d.relative_to(ROOT)}/")
    return True


def check_ollama() -> bool:
    hdr("Ollama")
    if shutil.which("ollama"):
        # Try to ping the REST API
        try:
            import urllib.request
            with urllib.request.urlopen("http://localhost:11434/api/tags", timeout=3) as resp:
                if resp.status == 200:
                    ok("Ollama is installed and running on localhost:11434")
                    return True
        except Exception:
            warn("Ollama binary found but the server does not appear to be running.")
            warn("  Start it with:  ollama serve")
            return True
    warn("Ollama not found — TFNK™ local LLM features will be unavailable.")
    warn("  Install: https://ollama.com/download")
    return True  # Non-fatal


def check_whisper_model() -> bool:
    hdr("faster-whisper model")
    # faster-whisper stores models in ~/.cache/huggingface/hub or a custom dir
    cache_root = Path.home() / ".cache" / "huggingface" / "hub"
    whisper_dirs = list(cache_root.glob("models--Systran--faster-whisper-*")) if cache_root.exists() else []
    if whisper_dirs:
        ok(f"faster-whisper model(s) found: {[d.name for d in whisper_dirs]}")
    else:
        warn("No faster-whisper model found in HuggingFace cache.")
        warn("  Download example:  python -c \"from faster_whisper import WhisperModel; WhisperModel('base')\"")
    return True  # Non-fatal


# ─── Summary ─────────────────────────────────────────────────────────────────

def print_summary(results: dict) -> None:
    hdr("Setup Summary")
    all_ok = True
    for name, passed in results.items():
        if passed:
            ok(name)
        else:
            err(name)
            all_ok = False

    print()
    if all_ok:
        print(f"{BOLD}{GREEN}All checks passed — TFNK™ is ready to launch!{RESET}")
        print(f"\n  {CYAN}Start the server:{RESET}  bash scripts/start.sh")
        print(f"  {CYAN}Windows:{RESET}           scripts\\start.bat")
    else:
        print(f"{BOLD}{YELLOW}Setup completed with warnings — address the errors above before launching.{RESET}")
    print()


# ─── Main ────────────────────────────────────────────────────────────────────

def main() -> int:
    print(f"""
{BOLD}{CYAN}  ████████╗███████╗███╗   ██╗██╗  ██╗
  ╚══██╔══╝██╔════╝████╗  ██║██║ ██╔╝
     ██║   █████╗  ██╔██╗ ██║█████╔╝
     ██║   ██╔══╝  ██║╚██╗██║██╔═██╗
     ██║   ██║     ██║ ╚████║██║  ██╗
     ╚═╝   ╚═╝     ╚═╝  ╚═══╝╚═╝  ╚═╝{RESET}
  {WHITE}TFNK™ Neural Agent Desktop — Setup{RESET}
""")

    results: dict[str, bool] = {}

    py_ok  = check_python()
    results["Python >= 3.11"] = py_ok
    if not py_ok:
        print_summary(results)
        return 1

    results["pip available"]          = check_pip()
    results["Dependencies installed"] = install_requirements()
    results[".env configured"]        = create_env()
    results["Directories created"]    = create_directories()

    # Non-fatal checks (always True return, but user sees warnings)
    check_ollama()
    check_whisper_model()

    print_summary(results)
    return 0 if all(results.values()) else 1


if __name__ == "__main__":
    sys.exit(main())
