// HUD Chat Dock — real chat sessions + messages. There is no LLM wired into this
// zero-dependency build, so chat does NOT fabricate an AI reply: it stores the
// user's message for real and answers with TFNK's own Intent Classifier (a real,
// deterministic analysis) plus an honest note that full agent execution requires
// delegating to Claude/Codex. Sessions and messages are genuinely persisted.

import { randomUUID } from "node:crypto";
import { classify } from "../agents/intent.js";
import { addLog } from "./store.js";

const sessions = new Map();

export function newSession({ agent = "tfnk", title } = {}) {
  const id = `chat_${randomUUID().slice(0, 8)}`;
  const s = { session_id: id, agent, title: title || `Chat ${sessions.size + 1}`, pinned_to_hud: false, messages: [], created_at: new Date().toISOString() };
  sessions.set(id, s);
  addLog({ agent: "ChatDock", event: "session_new", detail: { id, agent } });
  return s;
}

export function listSessions() {
  return [...sessions.values()].map((s) => ({ ...s, messages: undefined, message_count: s.messages.length }));
}
export function getSession(id) {
  return sessions.get(id) || null;
}

export function postMessage({ session_id, text } = {}) {
  if (!text || !String(text).trim()) return { error: "message text required" };
  let s = session_id ? sessions.get(session_id) : null;
  if (!s) s = newSession({});
  const userMsg = { role: "user", text: String(text), at: new Date().toISOString() };
  s.messages.push(userMsg);

  // Real, non-fabricated reply: classify intent and report honestly.
  const intent = classify(text);
  const reply = {
    role: "tfnk",
    text: `Understood as a "${intent.task_type}" task (risk ${intent.risk_level}). ` +
      (s.agent === "tfnk"
        ? `I can plan/verify this locally via the orchestrator. Full external execution would be delegated to Claude/Codex (no live agent is connected in this build).`
        : `No live ${s.agent} connection in this build — this message is recorded; delegate via the Delivery pipeline to execute.`),
    intent,
    honest_note: "TFNK reply generated by the local Intent Classifier; this build has no connected LLM, so no AI answer is fabricated.",
    at: new Date().toISOString(),
  };
  s.messages.push(reply);
  addLog({ agent: "ChatDock", event: "message", detail: { session_id: s.session_id, task_type: intent.task_type } });
  return { session_id: s.session_id, user: userMsg, reply };
}

export function pinToHud(id, pinned = true) {
  const s = sessions.get(id);
  if (!s) return { error: "session not found", _status: 404 };
  s.pinned_to_hud = pinned;
  return { session_id: id, pinned_to_hud: pinned };
}

export function _resetChatForTests() {
  sessions.clear();
}
